import { Page } from '@playwright/test';

const API_BASE = 'http://localhost:5000/api';

/** Generate a unique test user to avoid collisions between parallel runs. */
export function generateTestUser() {
  const id = Date.now().toString(36).slice(-6);
  return {
    name: `Test User ${id}`,
    username: `testuser_${id}`,
    email: `e2e_${id}@test.taskflow.app`,
    password: 'TestPass1!',
  };
}

/** Create a user via the API and return the full auth response (tokens + user). */
export async function createUserViaApi(user: { name: string; username: string; email: string; password: string }) {
  const res = await fetch(`${API_BASE}/auth/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(user),
  });
  if (!res.ok) {
    const body = await res.json();
    throw new Error(`Failed to create user: ${res.status} ${JSON.stringify(body)}`);
  }
  return res.json();
}

/** Log in and return the auth response. */
export async function loginViaApi(identifier: string, password: string) {
  const res = await fetch(`${API_BASE}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ identifier, password }),
  });
  if (!res.ok) {
    const body = await res.json();
    throw new Error(`Login failed: ${res.status} ${JSON.stringify(body)}`);
  }
  return res.json();
}

/** Verify an email via the API. */
export async function verifyEmailViaApi(token: string) {
  const res = await fetch(`${API_BASE}/auth/verify-email`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ token }),
  });
  return res.json();
}

/** Request a password reset via the API. */
export async function forgotPasswordViaApi(email: string) {
  const res = await fetch(`${API_BASE}/auth/forgot-password`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email }),
  });
  return res.json();
}

/** Reset a password via the API. */
export async function resetPasswordViaApi(token: string, newPassword: string) {
  const res = await fetch(`${API_BASE}/auth/reset-password`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ token, password: newPassword }),
  });
  return res.json();
}

/** Create a task for the authenticated user. */
export async function createTaskViaApi(accessToken: string, task: { title: string; description?: string; priority?: string; status?: string }) {
  const res = await fetch(`${API_BASE}/tasks`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${accessToken}`,
    },
    body: JSON.stringify(task),
  });
  if (!res.ok) {
    const body = await res.json();
    throw new Error(`Failed to create task: ${res.status} ${JSON.stringify(body)}`);
  }
  return res.json();
}

/** Get all tasks for the authenticated user. */
export async function getTasksViaApi(accessToken: string) {
  const res = await fetch(`${API_BASE}/tasks`, {
    headers: { 'Authorization': `Bearer ${accessToken}` },
  });
  if (!res.ok) throw new Error(`Failed to fetch tasks: ${res.status}`);
  return res.json();
}

/** Delete a task for the authenticated user. */
export async function deleteTaskViaApi(accessToken: string, taskId: string) {
  const res = await fetch(`${API_BASE}/tasks/${taskId}`, {
    method: 'DELETE',
    headers: { 'Authorization': `Bearer ${accessToken}` },
  });
  if (!res.ok) throw new Error(`Failed to delete task: ${res.status}`);
  return res.json();
}

/** Get the auth status (profile) for the user. */
export async function getProfileViaApi(accessToken: string) {
  const res = await fetch(`${API_BASE}/auth/profile`, {
    headers: { 'Authorization': `Bearer ${accessToken}` },
  });
  if (!res.ok) throw new Error(`Failed to get profile: ${res.status}`);
  return res.json();
}

/** Update user profile via the API. */
export async function updateProfileViaApi(accessToken: string, updates: Record<string, any>) {
  const res = await fetch(`${API_BASE}/auth/profile`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${accessToken}`,
    },
    body: JSON.stringify(updates),
  });
  if (!res.ok) {
    const body = await res.json();
    throw new Error(`Failed to update profile: ${res.status} ${JSON.stringify(body)}`);
  }
  return res.json();
}

/** Parse a verification token from an email. In the test environment, the API
 *  returns the verification token directly. For real email, you'd extract from
 *  the email link. */
export async function getVerificationToken(user: { email: string }) {
  // In the test environment, the verification token is generated by the server.
  // We need to fetch it from the user document indirectly.
  // For E2E tests, we use the resend-verification endpoint which returns the
  // verification info. In test mode, tokens are logged.
  return null; // Test-specific handling below
}

/** Store auth tokens and user info in localStorage for browser sessions. */
export async function setAuthInStorage(page: Page, auth: { accessToken: string; refreshToken: string; user: any }) {
  await page.evaluate(({ accessToken, refreshToken, user }) => {
    localStorage.setItem('accessToken', accessToken);
    localStorage.setItem('refreshToken', refreshToken);
    localStorage.setItem('user', JSON.stringify(user));
    // Set a flag that auth context can check on mount
    window.dispatchEvent(new Event('auth-storage-changed'));
  }, auth);
}

/** Clear auth from localStorage. */
export async function clearAuthInStorage(page: Page) {
  await page.evaluate(() => {
    localStorage.removeItem('accessToken');
    localStorage.removeItem('refreshToken');
    localStorage.removeItem('user');
    window.dispatchEvent(new Event('auth-storage-changed'));
  });
}
